version: '2.1'
volumes:
    node-red-data:
    node-red-test-data:
services:
  # The gateway itself
  ttn-resin-gateway-rpi:
    build:
      context: gateway
      args:
        GW_MACHINE_NAME:
    image: ttn-resin-gateway-rpi
    privileged: true
    network_mode: host
    restart: always
  mqtt:
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
  mqtt-test:
    image: panuwitp/mosquitto-arm
    ports:
      - "1884:1883"
  node-red:
    build: node-red
    volumes:
       - 'node-red-data:/data'
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always
  node-red-test:
    build: node-red-test
    volumes:
       - 'node-red-test-data:/data'
    ports:
       - "1882:1880"
    depends_on:
        - mqtt-test
    restart: always