version: '2'
volumes:
    balena-node-red-data:
    ttn-resin-gateway-rpi-data:
services:
balena-node-red:
    build: balena-node-red
    ports:
       - "1880:1880"
    privileged: true
    volumes:
       - 'balena-node-red-data:/data'
ttn-resin-gateway-rpi:
    build:ttn-resin-gateway-rpi
    privileged: true
    volumes:
       - 'ttn-resin-gateway-rpi-data:/data'
    restart: always