version: '2.1'
docker-compose build --no-cache
volumes:
    node-red-data:
    node-red-test-data:
    var_ttn_vol:
      driver: local
      driver_opts:
        type: tmpfs
        device: tmpfs
services:
  # The gateway itself
  gateway:
    build:
      context: gateway
      args:
        GW_MACHINE_NAME:
    image: amedee/ttn-gateway
    privileged: true
    network_mode: host
    restart: always
    devices:
      - "/dev/mem:/dev/mem"
    volumes:
      - var_ttn_vol:/var/ttn
  mqtt:
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
  mqtt-test:
    image: panuwitp/mosquitto-arm
    ports:
      - "1884:1883"
  node-red:
    build: node-red
    volumes:
       - 'node-red-data:/data'
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always
  node-red-test:
    build: node-red-test
    volumes:
       - 'node-red-test-data:/data'
    ports:
       - "1882:1880"
    depends_on:
        - mqtt-test
    restart: always